type: custom:navbar-card
routes:
  - url: /lovelace/default_view
    icon: mdi:home
    label: Home
  - url: /lovelace/default_view/devices
    icon: mdi:devices
    label: Devices
    hold_action:
      action: navigate
      navigation_path: /config/devices/dashboard
  - icon: mdi:microsoft-visual-studio-code
    label: Vscode
    url: /hassio/ingress/a0d7b954_vscode
  - url: /config/dashboard
    icon: mdi:cog
    label: Settings
  - icon: mdi:dots-horizontal
    label: More
    tap_action:
      action: open-popup
    popup:
      - icon: mdi:cog
        url: /config/dashboard
      - icon: mdi:hammer
        url: /developer-tools/yaml
      - icon: mdi:power
        tap_action:
          action: call-service
          service: homeassistant.restart
          service_data: {}
          confirmation:
            text: Are you sure you want to restart Home Assistant?
styles: |-
  .navbar-card {
    --navbar-primary-color: rgba(255, 255, 255, 0.35);
    background: transparent;
  }

  .popup-item .button {
    border: 2px solid rgba(255, 255, 255, 0.2);
    border-radius: 20px;
    box-shadow: 0 12px 48px rgba(31, 38, 135, 0.154);
    background-image: linear-gradient(135deg, rgba(255, 255, 255, 0.1), transparent 50%);
    background: transparent;
  }
layout:
  auto_padding:
    desktop_px: 20
    mobile_px: 20
mobile:
  mode: floating
desktop:
  position: bottom
